### ISSUE TITLE
Add 'request' package as a dependency

### ISSUE THREAD

**Issue by Baa14453** [c-klinger/MMM-JsonValue#4]
Hi,
When trying I got the below error:
```
0|mm       | Require stack:
0|mm       | - /home/mirror/MagicMirror/modules/MMM-JsonValue/node_helper.js
0|mm       | - /home/mirror/MagicMirror/js/app.js
0|mm       | - /home/mirror/MagicMirror/js/electron.js
0|mm       | - /home/mirror/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm       | - 
0|mm       |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|mm       |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|mm       |     at Function.Module._resolveFilename (/home/mirror/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm       |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|mm       |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm       |     at Object.<anonymous> (/home/mirror/MagicMirror/modules/MMM-JsonValue/node_helper.js:11:15)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm       | [30.10.2021 00:32.22.143] [ERROR] Whoops! There was an uncaught exception...
0|mm       | [30.10.2021 00:32.22.151] [ERROR] Error: Cannot find module 'request'
0|mm       | Require stack:
0|mm       | - /home/mirror/MagicMirror/modules/MMM-JsonValue/node_helper.js
0|mm       | - /home/mirror/MagicMirror/js/app.js
0|mm       | - /home/mirror/MagicMirror/js/electron.js
0|mm       | - /home/mirror/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm       | - 
0|mm       |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|mm       |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|mm       |     at Function.Module._resolveFilename (/home/mirror/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm       |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|mm       |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm       |     at Object.<anonymous> (/home/mirror/MagicMirror/modules/MMM-JsonValue/node_helper.js:11:15)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
0|mm       |   code: 'MODULE_NOT_FOUND',
0|mm       |   requireStack: [
0|mm       |     '/home/mirror/MagicMirror/modules/MMM-JsonValue/node_helper.js',
0|mm       |     '/home/mirror/MagicMirror/js/app.js',
0|mm       |     '/home/mirror/MagicMirror/js/electron.js',
0|mm       |     '/home/mirror/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|mm       |     undefined
0|mm       |   ]
0|mm       | }
0|mm       | [30.10.2021 00:32.22.152] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [30.10.2021 00:32.22.153] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

This resolved after installing `request` through `npm install request` inside the MMM-JsonValue module directory, I guess it's a dependency idk

**Comment by c-klinger** [comment]
Hi, thanks for the report. This should be in fact an issue for some time now (since release v2.15.0, https://github.com/MichMich/MagicMirror/pull/2474) when the main project replaced `request `with `node-fetch`.
As request package is deprecated for some time now this makes sense and might be an improvement to this module as well. 
Anyways as quick fix adding the dependency should work.
